version: '3'

services:

  php:
    container_name: booking-backend.dev_php
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../../:/var/www/booking-backend-app
    restart: unless-stopped
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www/booking-backend-app
    networks:
      - booking-backend-network

  mysql:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: booking-backend.dev_mysql
    restart: unless-stopped
    tty: true
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5432:3306"
    expose:
      - 5432
    networks:
      - booking-backend-network

  nginx:
    container_name: booking-backend.dev_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../../:/var/www/booking-backend-app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    networks:
      - booking-backend-network
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

volumes:
  mysqldata:
    driver: local

networks:
  booking-backend-network:
    driver: bridge
